baseURL: "https://pranaychakilam.github.io/portfolio/"
languageCode: en-us
title: Pranay Chakilam
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: certifications
      name: Certifications
      url: /certifications
      weight: 50
    - identifier: projects
      name: Projects
      url: /projects
      weight: 40
    - identifier: experience
      name: Experience
      url: /experience
      weight: 20
    - identifier: search
      name: Search
      url: /search
      weight: 60
    - identifier: recommendations
      name: Recommendations
      url: /recommendations
      weight: 60

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Pranay Chakilam"
    subtitle: Hi 👋! I'm Pranay, a highly motivated and experienced problem solver with a passion for data science and have 2+ years of experience leveraging data to provide actionable insights and business solutions to clients and organizations. I have an excellent command of business operations and analytics tools with the ability to visualize the Big Picture from a 360-degree view yielding highly effective analysis and communication. I am logical, able to grasp new concepts, incorporate innovations, and stay up to date with industry and business standards.
    imageUrl: "home/formal-pic-small.png"
    imageWidth: 220
    imageHeight: 220
    buttons:
      - name: Resume
        url: "https://drive.google.com/file/d/1Vrf34hDqpf11yTAyhTV_tYR0w7GGTcLP/view?usp=drive_link"

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:pranaychakilam999@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/pranay-chakilam"
    - name: "github"
      url: "https://github.com/pranaychakilam"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
